"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import firebase_admin
from firebase_admin import credentials

# Path to your Firebase Admin SDK private key
service_account_path = '/home/pehlivanoglu/Desktop/mail_enc/server/connection.json'

# Initialize Firebase with your credentials
cred = credentials.Certificate({
  "type": "service_account",
  "project_id": "mail-enc",
  "private_key_id": "273fe1464dd590197c75b4e12bc07b3afa5731c0",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDaRTDYQnRMRxbA\n+CJaqoKAeHBc9zfv/oCSJKF2P6OAvS10ncJdv/kWNFV4o3q7Z55wFLJahHlUHt7t\nhsvGZ+a3+Qu1v1CsCrloz21zUPvm6kB+gvSqIPUI4AxyxRhA6m8AB7x1my/TPFTN\ncJygUrGwwIfTElXT3Y96FbwaIrTyRS9ys5PAlnuEGcD4zDurPcnE3TNpZuE/SE5T\nC4PRIulwyKLDXYgGFCSm5tbYYE7WmidOxwrVOJZ0iOrXKWs165m8AbAU5VBrQqsp\ndHDJeYjIhDOuBVijldAJWxoqrPjdkUuwWTeoqcHWoG9N+9BrdqSO/ZvfIhimr/YB\n3C6edddxAgMBAAECggEADhZgzdcS1ijRF/j2j/8o921j5H7Tk5VLq2MFhXIbtZTq\n000qp3iwSmsWnc0rVYodXeLav2CFINVHPRxcmDx01dM98BKI0eR1TVr0l6NBRt4/\n9bUHtoKfCLNxNOfHUMqbXxdLZhRzNJZ/FgKv0TcqdHEmCGJKu3xgJMM0sJkkhZhW\nphCaNdrYbCQJvYgGqM0TrX+vDrbFh4Uh5UBuFj/s6XNu9ClsP8ygtDaq5MpQ0PCd\nadqKYfGKfZj3rt33idX10C95+qD20VPdSwzMCtnl5+t+k1Qx6EeiY1gFSz5dvSgE\n9OkRiH/kOyQOAewhLMxmUiiOgcJ6tVWFmiCUZrHSOQKBgQD5cu8kTLCTMjmW51Jj\nj7T/CexfjmysdXvv47cYxfckfpFxeQgiUk2lra9q2sjLLTWf24/nfgqvchIBZwgD\ncopwC6vhPeolY8/l9WQm17ETiCZFjMyumtvoXT9dSUqnjAGGXm70VXdqc6GkpTsm\nXHfbLCFp/JYX5ijOnZaZIYGr7QKBgQDgAKPJePAwi03EhHZu63xBRN6oRnnDRVMy\nqfn8tdqMZ8zKKhUjS68k6mLcQyjsVwvC9zpPry8BgAAwrEK1YAMFbVG7oKpncXFC\nkh7Er2dQX75nPvY8j39EyZacO5KyQ6A0tK0ZLVL/2/E3LWjZsbIBtXsRAx5wYxE6\nzN+5DwgRFQKBgF92zfCNbPIYQZPv2UcDA1ireoujXRGvMIxBEJxpfsi3q3/KuwMv\njkm+q6hwLHIdTi1sgKkuQnacaCmjPZzcJAD3ZoMgB9DhXvn5rKd02m7IJyVs2hRk\nbY6CyTIxT2HJoffDgiD96GKT+COjnHx03OXDANKn+OUSj0Fra+wUt6SNAoGAEYYb\nShyq9bFAMTqHpV/IxbZkkNeKmQsoWhNQGkQDx+4q6Dnok21NU17+wuqCHhMlOWhr\n6GX1EHH6EdS4F0ZeliMaPMpx6kvGp4WU4KA0PeZvl9YmH1C+jRwUKz7B2C5QLy9f\nR1PzZU7IjR+BT16GZXnUGd2bmQE3DNmQOwMBB40CgYAgfAa2a5V0oQIXXCOymmL3\nuEZqITnhk03wi4PLMEUJtUpzCzSX3zhijxO53nvpeUufMnf7tivVvY+KT5OPP9u0\nH/C6uWTUGc6QqRD21u64kPK54p8bRaiz6n7ZC9pZFe1zC/HKRi+6u+y1vJxN+FZY\nGaJWHxtDZwvm9uPJniKOsg==\n-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-1sffa@mail-enc.iam.gserviceaccount.com",
  "client_id": "115682718021327074573",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-1sffa%40mail-enc.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
})
try:
    firebase_admin.initialize_app(cred)
except Exception:
    print("cred")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4@(708+r+f98lc3zlhp3tnir6w7t$mxj5+6!w1yt5jq*dnd2wb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_extensions',
    'authentication',
    'rsa_transfer'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join("/home/pehlivanoglu/Desktop/mail_enc/server/api", 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
